package com.mycompany.bankacibitir;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
public class BankaciEklesin extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public BankaciEklesin() {
        initComponents();
        conn =Baglanti.connecrb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bnk_mst_ekl_kll = new javax.swing.JTextField();
        bnk_mst_ekl_sfr = new javax.swing.JTextField();
        mst_ekle_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bnk_mst_ekl_adi = new javax.swing.JTextField();
        bnk_mst_ekl_bky = new javax.swing.JTextField();
        bnk_mst_ekl_sadi = new javax.swing.JTextField();
        check_hsb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 245, 245));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Müşteri Ekleme Menüsü");

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("GERİ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Eklemek istediğiniz müşterinin şifresini giriniz: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Eklemek istediğiniz müşterinin kullanıcı adını giriniz: ");

        bnk_mst_ekl_kll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_kllActionPerformed(evt);
            }
        });

        bnk_mst_ekl_sfr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_sfrActionPerformed(evt);
            }
        });

        mst_ekle_btn.setBackground(new java.awt.Color(0, 153, 153));
        mst_ekle_btn.setText("Müşteri Ekle");
        mst_ekle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mst_ekle_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Eklemek istediğiniz müşterinin soyadını giriniz: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Eklemek istediğiniz müşterinin adını giriniz: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Eklemek istediğiniz müşterinin hesap sayısını seçiniz:");

        bnk_mst_ekl_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_adiActionPerformed(evt);
            }
        });

        bnk_mst_ekl_bky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_bkyActionPerformed(evt);
            }
        });

        bnk_mst_ekl_sadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_sadiActionPerformed(evt);
            }
        });

        check_hsb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        check_hsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_hsbActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Eklemek istediğiniz müşterinin bakiyesini giriniz: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bnk_mst_ekl_sfr)
                        .addComponent(bnk_mst_ekl_bky, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addComponent(bnk_mst_ekl_sadi)
                        .addComponent(bnk_mst_ekl_adi)
                        .addComponent(bnk_mst_ekl_kll))
                    .addComponent(check_hsb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mst_ekle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bnk_mst_ekl_kll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnk_mst_ekl_sfr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnk_mst_ekl_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnk_mst_ekl_sadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnk_mst_ekl_bky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_hsb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mst_ekle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Bankaci mg=new Bankaci();
        mg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mst_ekle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mst_ekle_btnActionPerformed
        String musteriKullanici=bnk_mst_ekl_kll.getText();
        String musteriPassword=bnk_mst_ekl_sfr.getText();
        String musteriAdi=bnk_mst_ekl_adi.getText();
        String musteriSoyadi=bnk_mst_ekl_sadi.getText();
        int musteriBakiye=Integer.parseInt(bnk_mst_ekl_sfr.getText());
        int hesapSayisi=Integer.parseInt((String) check_hsb.getSelectedItem());
        String musteriHesabi1="hesap1";
        String musteriHesabi2="hesap2";
        String musteriHesabi3="hesap3";
        String queryStringi="";
        switch (hesapSayisi) {
            case 1:queryStringi="INSERT INTO musteri"
                + "VALUES ('"+musteriKullanici+"','"+musteriAdi+"','"+musteriSoyadi+"','"+musteriBakiye+"','"+musteriHesabi1+"','NULL','NULL','"+musteriPassword+"')";
        
                
                break;
            case 2:queryStringi="INSERT INTO musteri "
                + "VALUES ('"+musteriKullanici+"','"+musteriAdi+"','"+musteriSoyadi+"','"+musteriBakiye+"','"+musteriHesabi1+"','"+musteriHesabi2+"','NULL','"+musteriPassword+"')";
        
                
                break;
            case 3:queryStringi="INSERT INTO musteri "
                + "VALUES ('"+musteriKullanici+"','"+musteriAdi+"','"+musteriSoyadi+"','"+musteriBakiye+"','"+musteriHesabi1+"','"+musteriHesabi2+"','"+musteriHesabi3+"','"+musteriPassword+"')";
        
                
                break;
            default:
                throw new AssertionError();
        }
        
        try {
            pst=conn.prepareStatement(queryStringi);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Müşteri eklendi.");
           
            
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mst_ekle_btnActionPerformed

    private void bnk_mst_ekl_kllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_kllActionPerformed
       
        
    }//GEN-LAST:event_bnk_mst_ekl_kllActionPerformed

    private void bnk_mst_ekl_sfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_sfrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_sfrActionPerformed

    private void bnk_mst_ekl_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_adiActionPerformed

    private void bnk_mst_ekl_bkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_bkyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_bkyActionPerformed

    private void bnk_mst_ekl_sadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_sadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_sadiActionPerformed

    private void check_hsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_hsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_hsbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankaciEklesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankaciEklesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankaciEklesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankaciEklesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankaciEklesin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bnk_mst_ekl_adi;
    private javax.swing.JTextField bnk_mst_ekl_bky;
    private javax.swing.JTextField bnk_mst_ekl_kll;
    private javax.swing.JTextField bnk_mst_ekl_sadi;
    private javax.swing.JTextField bnk_mst_ekl_sfr;
    private javax.swing.JComboBox<String> check_hsb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mst_ekle_btn;
    // End of variables declaration//GEN-END:variables
}
