package com.mycompany.bankacibitir;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
public class BankaciDuzenlesin extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public BankaciDuzenlesin() {
        initComponents();
        conn =Baglanti.connecrb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bnk_mst_ekl_bkye = new javax.swing.JTextField();
        bnk_mst_ekl_kll = new javax.swing.JTextField();
        mst_dznle_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bnk_mst_ekl_sifre = new javax.swing.JTextField();
        bnk_mst_ekl_soyadi = new javax.swing.JTextField();
        bnk_mst_ekl_adii = new javax.swing.JTextField();
        check_hsb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bnk_mst_eskl_kll = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 245, 245));

        jPanel2.setBackground(new java.awt.Color(63, 245, 245));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Müşteri Düzenleme Menüsü");

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("GERİ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Düzenlemek istediğiniz müşterinin şifresini giriniz: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Düzenlemek istediğiniz müşterinin kullanıcı adını giriniz: ");

        bnk_mst_ekl_bkye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_bkyeActionPerformed(evt);
            }
        });

        bnk_mst_ekl_kll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_kllActionPerformed(evt);
            }
        });

        mst_dznle_btn.setBackground(new java.awt.Color(0, 153, 153));
        mst_dznle_btn.setText("Müşteri Düzenle");
        mst_dznle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mst_dznle_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Düzenlemek istediğiniz müşterinin soyadını giriniz: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Düzenlemek istediğiniz müşterinin adını giriniz: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Düzenlemek istediğiniz müşterinin hesap sayısını seçiniz:");

        bnk_mst_ekl_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_sifreActionPerformed(evt);
            }
        });

        bnk_mst_ekl_soyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_soyadiActionPerformed(evt);
            }
        });

        bnk_mst_ekl_adii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_ekl_adiiActionPerformed(evt);
            }
        });

        check_hsb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        check_hsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_hsbActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Düzenlemek istediğiniz müşterinin bakiyesini giriniz: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Düzenlemek istediğiniz müşterinin eski kullanıcı adını giriniz: ");

        bnk_mst_eskl_kll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnk_mst_eskl_kllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(mst_dznle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bnk_mst_ekl_kll)
                                .addComponent(bnk_mst_ekl_soyadi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(bnk_mst_ekl_adii)
                                .addComponent(bnk_mst_ekl_sifre))
                            .addComponent(check_hsb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnk_mst_ekl_bkye, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnk_mst_eskl_kll, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bnk_mst_ekl_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(bnk_mst_ekl_adii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bnk_mst_eskl_kll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bnk_mst_ekl_kll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bnk_mst_ekl_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(bnk_mst_ekl_bkye, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_hsb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mst_dznle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check_hsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_hsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_hsbActionPerformed

    private void bnk_mst_ekl_adiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_adiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_adiiActionPerformed

    private void bnk_mst_ekl_soyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_soyadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_soyadiActionPerformed

    private void bnk_mst_ekl_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_sifreActionPerformed

    private void mst_dznle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mst_dznle_btnActionPerformed
        
        String musteriEskiKullanici=bnk_mst_eskl_kll.getText();
        String musteriKullanici=bnk_mst_ekl_kll.getText();
        String musteriPassword=bnk_mst_ekl_sifre.getText();
        String musteriAdi=bnk_mst_ekl_adii.getText();
        String musteriSoyadi=bnk_mst_ekl_soyadi.getText();
        int musteriBakiye=Integer.parseInt(bnk_mst_ekl_bkye.getText());
        int hesapSayisi=Integer.parseInt((String) check_hsb.getSelectedItem());
        String musteriHesabi1="hesap1";
        String musteriHesabi2="hesap2";
        String musteriHesabi3="hesap3";
        String queryStringi="";
        switch (hesapSayisi) {
            case 1:queryStringi="UPDATE musteri SET mst_kll='"+musteriKullanici+"',mst_adi='"+musteriAdi+"',mst_sadi='"+musteriSoyadi+"',mst_bky='"+musteriBakiye+"',mst_hsb='"+musteriHesabi1+"',mst_hsb2='NULL',mst_hsb3='NULL',mst_sfr='"+musteriPassword+"'WHERE mst_kll='"+musteriEskiKullanici+"'";
            break;
            case 2:queryStringi="UPDATE musteri SET mst_kll='"+musteriKullanici+"',mst_adi='"+musteriAdi+"',mst_sadi='"+musteriSoyadi+"',mst_bky='"+musteriBakiye+"',mst_hsb='"+musteriHesabi1+"',mst_hsb2='"+musteriHesabi2+"',mst_hsb3='NULL',mst_sfr='"+musteriPassword+"'WHERE mst_kll='"+musteriEskiKullanici+"'";
            break;
            case 3:queryStringi="UPDATE musteri SET mst_kll='"+musteriKullanici+"',mst_adi='"+musteriAdi+"',mst_sadi='"+musteriSoyadi+"',mst_bky='"+musteriBakiye+"',mst_hsb='"+musteriHesabi1+"',mst_hsb2='"+musteriHesabi2+"',mst_hsb3='"+musteriHesabi3+"',mst_sfr='"+musteriPassword+"'WHERE mst_kll='"+musteriEskiKullanici+"'";
            break;
            default:
            throw new AssertionError();
        }

        try {
            pst=conn.prepareStatement(queryStringi);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Müşteri düzenlendi.");

        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mst_dznle_btnActionPerformed

    private void bnk_mst_ekl_kllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_kllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_ekl_kllActionPerformed

    private void bnk_mst_ekl_bkyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_ekl_bkyeActionPerformed

    }//GEN-LAST:event_bnk_mst_ekl_bkyeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Bankaci mg=new Bankaci();
        mg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bnk_mst_eskl_kllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnk_mst_eskl_kllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnk_mst_eskl_kllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenlesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenlesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenlesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankaciDuzenlesin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankaciDuzenlesin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bnk_mst_ekl_adii;
    private javax.swing.JTextField bnk_mst_ekl_bkye;
    private javax.swing.JTextField bnk_mst_ekl_kll;
    private javax.swing.JTextField bnk_mst_ekl_sifre;
    private javax.swing.JTextField bnk_mst_ekl_soyadi;
    private javax.swing.JTextField bnk_mst_eskl_kll;
    private javax.swing.JComboBox<String> check_hsb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mst_dznle_btn;
    // End of variables declaration//GEN-END:variables
}
